name: 1_First job

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: enter enbvironment vale

      space:
        type: string
        required: true
        description: enter space value



jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      env_var_a : "abc"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run : |
          pip install -e ".[dev]"
      - name: List installedDependencies
        run: |
          pip list
      - name: Run Unit tests
        run: |
          pytest me/personal --cov
      - name: List environment Variables
        run: |
          print(os.environ)
  run:
    needs: build
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      env_var_b : "def"
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: runcode
        run: |
          python ./me/personal/perform_calc/run_code.py
          



